### ISSUE TITLE
LWCQuestion no TrueFalse option

### ISSUE THREAD

**Issue by kisame348** [revaturelabs/TrialoftheTitans#449]
LWCQuestion no TrueFalse option

**Comment by kisame348** [comment]
Make a trigger on question when question Type= True-False set the options to TRUE||FALSE

**Comment by hamidzain** [comment]
Resolved as of commit https://github.com/revaturelabs/TrialoftheTitans/commit/cc41192607476e9167d5111f9d8ad9dec6a6cd9f, including testing. Closing.
